const retos = {
  divertido: [
    "{jugador1}, imita a un gato durante 30 segundos.",
    "{jugador1}, hazle una declaración de amor dramática a {jugador2}.",
    "{jugador1}, canta el estribillo de tu canción favorita sin equivocarte.",
    "{jugador1}, haz una pose de superhéroe durante 10 segundos.",
    "{jugador1}, baila como un robot durante 15 segundos.",
    "{jugador1}, inventa una historia con {jugador2} como protagonista.",
    "{jugador1}, actúa como si tuvieras miedo de tu propia sombra.",
    "{jugador1}, habla con acento italiano hasta tu próximo turno.",
    "{jugador1}, haz un chiste malo y ríete como si fuera genial.",
    "{jugador1}, camina en cámara lenta durante 20 segundos.",
    "{jugador1}, juega a ser un influencer exagerado por un minuto.",
    "{jugador1}, canta todo lo que digas durante una ronda.",
    "{jugador1}, finge que estás en una telenovela y exagera tus reacciones.",
    "{jugador1}, haz mímica de una película famosa y que {jugador2} la adivine.",
    "{jugador1}, haz una imitación de tu profesor más aburrido.",
    "{jugador1}, dramatiza una pelea entre dos verduras.",
    "{jugador1}, lanza un piropo absurdo a {jugador2}.",
    "{jugador1}, da una clase sobre cómo preparar un sándwich con estilo.",
    "{jugador1}, haz un tutorial de maquillaje invisible.",
    "{jugador1}, presume de tu talento oculto... aunque no lo tengas.",
    "{jugador1}, haz de narrador épico de lo que haga {jugador2} por 1 minuto.",
    "{jugador1}, invéntate un trabalenguas y dilo rápido.",
    "{jugador1}, haz como si fueras un perro contento que encuentra una pelota.",
    "{jugador1}, hazle una entrevista ridícula a {jugador2}.",
    "{jugador1}, actúa como si tu silla fuera un caballo salvaje.",
    "{jugador1}, crea un nuevo saludo secreto con {jugador2}.",
    "{jugador1}, cambia el nombre de todos los jugadores a apodos absurdos.",
    "{jugador1}, baila como si nadie te estuviera viendo (aunque sí lo hagan).",
    "{jugador1}, haz de DJ con efectos de sonido por 15 segundos.",
    "{jugador1}, dramatiza tu desayuno como si fuera una tragedia griega.",
    "{jugador1}, dramatiza una película de acción usando solo sonidos.",
    "{jugador1}, haz un comercial absurdo de un producto inventado.",
    "{jugador1}, inventa una canción sobre el color azul.",
    "{jugador1}, interpreta una escena de celos con {jugador2} como ex ficticio.",
    "{jugador1}, describe a {jugador2} como si fuera una estrella de Hollywood.",
    "{jugador1}, actúa como si estuvieras en gravedad cero.",
    "{jugador1}, haz un anuncio político para convertirte en presidente del grupo.",
    "{jugador1}, cambia tu forma de hablar a medieval durante dos turnos.",
    "{jugador1}, dramatiza una escena de despedida como si fueras actor de novela.",
    "{jugador1}, haz una coreografía improvisada con {jugador2}.",
    "{jugador1}, habla como robot hasta que otro te libere.",
    "{jugador1}, dramatiza una entrevista con una cucaracha famosa.",
    "{jugador1}, improvisa un poema para {jugador2}.",
    "{jugador1}, haz como si tu celular te hablara.",
    "{jugador1}, canta como si fueras un cantante de ópera.",
    "{jugador1}, haz como si fueras una celebridad siendo entrevistada.",
    "{jugador1}, inventa una palabra nueva y úsala en una frase lógica.",
    "{jugador1}, dramatiza cómo reaccionas cuando te cancelan un plan genial.",
    "{jugador1}, explica tu día como si fuera una aventura épica.",
    "{jugador1}, actúa como si acabaras de descubrir que eres un mago."
  ],
  picante: [
    "{jugador1}, susurra algo atrevido al oído de {jugador2}.",
    "{jugador1}, describe cómo besarías a {jugador2}.",
    "{jugador1}, besa la mano de {jugador2} como en una película romántica.",
    "{jugador1}, elige entre {jugador2} y {jugador3} para una cita sorpresa.",
    "{jugador1}, di a quién besarías entre {jugador2}, {jugador3} y {jugador4}.",
    "{jugador1}, baila sensual para {jugador2}.",
    "{jugador1}, cuéntale a {jugador2} un secreto erótico (sin detalles explícitos).",
    "{jugador1}, deja que {jugador2} te haga una pregunta picante y respóndela.",
    "{jugador1}, toma la mano de {jugador2} y míralo fijamente durante 10 segundos.",
    "{jugador1}, elige a alguien para darle un masaje de hombros durante 20 segundos.",
    "{jugador1}, comparte la fantasía más atrevida que tengas (modo sugerente).",
    "{jugador1}, da un beso soplado a cada jugador del grupo.",
    "{jugador1}, manda un mensaje de voz sexy a un contacto aleatorio (simulado).",
    "{jugador1}, deja que {jugador2} elija un reto picante para ti.",
    "{jugador1}, simula besar a {jugador2} sin contacto real.",
    "{jugador1}, menciona tu parte favorita del cuerpo de {jugador2} y por qué.",
    "{jugador1}, acaricia simbólicamente el rostro de {jugador2} (sin tocar).",
    "{jugador1}, imagina una escena romántica con {jugador2} e interprétala.",
    "{jugador1}, baila lento con {jugador2} al ritmo que imagines.",
    "{jugador1}, haz una pregunta íntima a {jugador2} y responde tú también.",
    "{jugador1}, elige entre besar, abrazar o mirar intensamente a {jugador2}.",
    "{jugador1}, ¿cuál de los jugadores crees que es mejor besando?",
    "{jugador1}, canta una canción romántica mirando a {jugador2}.",
    "{jugador1}, intercambia una mirada intensa con {jugador2} durante 8 segundos.",
    "{jugador1}, describe a {jugador2} con un adjetivo picante.",
    "{jugador1}, simula un roce de manos accidental con {jugador2}.",
    "{jugador1}, besa a tu derecha o izquierda (el jugador más cercano).",
    "{jugador1}, haz una confesión atrevida que nunca hayas dicho.",
    "{jugador1}, nombra con quién tendrías una cita a ciegas aquí.",
    "{jugador1}, quédate mirando fijamente a {jugador2} hasta tu siguiente turno.",
    "{jugador1}, haz una mirada sexy y mantenla 5 segundos.",
    "{jugador1}, intercambia un cumplido subido de tono con {jugador2}.",
    "{jugador1}, pregúntale a {jugador2} si quiere darte un reto picante extra.",
    "{jugador1}, di quién crees que es más atrevido entre {jugador2}, {jugador3} y tú.",
    "{jugador1}, lanza un beso aéreo a quien tú elijas.",
    "{jugador1}, pídele a {jugador2} que te enseñe cómo seduce.",
    "{jugador1}, haz contacto visual con {jugador2} mientras dices un piropo sensual.",
    "{jugador1}, invéntate una escena de película romántica con {jugador2}.",
    "{jugador1}, nombra tres cosas sensuales que harías en una cita ideal.",
    "{jugador1}, da tu opinión sobre quién tiene la mejor voz sexy aquí.",
    "{jugador1}, crea un nuevo apodo picante para {jugador2}.",
    "{jugador1}, escribe una frase sexy para usar en una cita.",
    "{jugador1}, elige a quién darías tu número en una fiesta.",
    "{jugador1}, describe la cita perfecta con {jugador2} en menos de 10 palabras.",
    "{jugador1}, ¿qué harías si tú y {jugador2} quedaran encerrados solos?",
    "{jugador1}, nombra a tres personas del grupo con las que podrías tener química.",
    "{jugador1}, define el estilo de besar de {jugador2} (sin haberlo probado).",
    "{jugador1}, imagina que tú y {jugador2} están en una escena de película adulta (modo sugerente)."
  ],
  incómodo: [
    "{jugador1}, cuenta un secreto vergonzoso de tu infancia.",
    "{jugador1}, ¿qué es lo más raro que haces cuando estás solo/a?",
    "{jugador1}, dile a {jugador2} lo que menos te gusta de su personalidad."
  ]
};